"""Action adapter protocol — environment-specific action space abstraction.

Each environment implements its own ActionAdapter. The LLM policy holds
one adapter and delegates action-space knowledge to it. This keeps the
policy backbone and RL updater environment-agnostic.

Two output modes share the same interface:
  - Action head mode: forward_logits(hidden) → discrete logits
  - Free decoding mode: decode_text(text) → action index

Both are optional — an adapter may support one or both depending on
the environment and training stage.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from torch import Tensor


@runtime_checkable
class ActionAdapter(Protocol):
    """Environment-specific action space adapter.

    Implementations live under envs/<env_name>/action_adapter.py.
    The LLM policy imports only this protocol, never the concrete class.
    """

    @property
    def num_actions(self) -> int:
        """Number of discrete actions in this environment."""
        ...

    def forward_logits(self, hidden_states: Tensor) -> Tensor:
        """Map LLM hidden states to action logits.

        Args:
            hidden_states: (B, D) — last-layer hidden from the LLM backbone.

        Returns:
            logits: (B, num_actions) — unnormalized log-probabilities.
        """
        ...

    def decode_text(self, text: str) -> int | None:
        """Parse free-form text output into an action index.

        Args:
            text: raw text generated by the LLM.

        Returns:
            Action index in [0, num_actions), or None if parsing fails.
        """
        ...

    def format_action(self, action: int) -> str:
        """Convert action index to human-readable text.

        Used for logging, SFT data construction, and free-decoding prompts.

        Args:
            action: index in [0, num_actions).

        Returns:
            Text representation (e.g. "up", "push_right").
        """
        ...
